name: C++ Payment Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install g++
      - name: Install g++ and make
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Compile the tests
      - name: Compile Payment Tests
        run: g++ -std=c++17 PaymentProcessor.cpp Checkout.cpp PaymentTest.cpp -o PaymentTest.exe

      # Step 4: Run the tests
      - name: Run Payment Tests
        run: ./PaymentTest.exe
